module.exports = {
  FETCH_KEY_FROM_STORAGE: 'fetch-key-from-storage',
  SAVE_KEY_TO_STORAGE: 'save-key-to-storage',
  HANDLE_FETCH_KEY_FROM_STORAGE: 'handle-fetch-key-from-storage',
  HANDLE_SAVE_KEY_TO_STORAGE: 'handle-save-key-to-storage',
  POLLING_INTERVAL: 1000,
  DEFAULT_PICK_FILE_MESSAGE:
    ' - It is usually located in C:\\Program Files (x86)\\Grinding Gear Games\\Path of Exile\\logs\\Client.txt',
  QUEUE_SIZE: 5,
  LANGUAGES: [
    { af: 'Afrikaans' },
    { sq: 'Albanian' },
    { am: 'Amharic' },
    { ar: 'Arabic' },
    { hy: 'Armenian' },
    { az: 'Azeerbaijani' },
    { eu: 'Basque' },
    { be: 'Belarusian' },
    { bn: 'Bengali' },
    { bs: 'Bosnian' },
    { bg: 'Bulgarian' },
    { ca: 'Catalan' },
    { ce: 'Cebuanob' },
    { 'zh-CN': 'Chinese' },
    { 'zh-TW': 'Chinese' },
    { co: 'Corsican' },
    { hr: 'Croatian' },
    { cs: 'Czech' },
    { da: 'Danish' },
    { nl: 'Dutch' },
    { en: 'English' },
    { eo: 'Esperanto' },
    { et: 'Estonian' },
    { fi: 'Finnish' },
    { fr: 'French' },
    { fy: 'Frisian' },
    { gl: 'Galician' },
    { ka: 'Georgian' },
    { de: 'German' },
    { el: 'Greek' },
    { gu: 'Gujarati' },
    { ht: 'Haitian Creole' },
    { ha: 'Hausa' },
    { ha: 'Hawaiianw' },
    { he: 'Hebrew**' },
    { hi: 'Hindi' },
    { hm: 'Hmongn' },
    { hu: 'Hungarian' },
    { is: 'Icelandic' },
    { ig: 'Igbo' },
    { id: 'Indonesian' },
    { ga: 'Irish' },
    { it: 'Italian' },
    { ja: 'Japanese' },
    { jw: 'Javanese' },
    { kn: 'Kannada' },
    { kk: 'Kazakh' },
    { km: 'Khmer' },
    { ko: 'Korean' },
    { ku: 'Kurdish' },
    { ky: 'Kyrgyz' },
    { lo: 'Lao' },
    { la: 'Latin' },
    { lv: 'Latvian' },
    { lt: 'Lithuanian' },
    { lb: 'Luxembourgish' },
    { mk: 'Macedonian' },
    { mg: 'Malagasy' },
    { ms: 'Malay' },
    { ml: 'Malayalam' },
    { mt: 'Maltese' },
    { mi: 'Maori' },
    { mr: 'Marathi' },
    { mn: 'Mongolian' },
    { my: 'Myanmar (Burmese)' },
    { ne: 'Nepali' },
    { no: 'Norwegian' },
    { ny: 'Nyanja (Chichewa)' },
    { ps: 'Pashto' },
    { fa: 'Persian' },
    { pl: 'Polish' },
    { pt: 'Portuguese (Portugal, Brazil)' },
    { pa: 'Punjabi' },
    { ro: 'Romanian' },
    { ru: 'Russian' },
    { sm: 'Samoan' },
    { gd: 'Scots Gaelic' },
    { sr: 'Serbian' },
    { st: 'Sesotho' },
    { sn: 'Shona' },
    { sd: 'Sindhi' },
    { si: 'Sinhala (Sinhalese)' },
    { sk: 'Slovak' },
    { sl: 'Slovenian' },
    { so: 'Somali' },
    { es: 'Spanish' },
    { su: 'Sundanese' },
    { sw: 'Swahili' },
    { sv: 'Swedish' },
    { tl: 'Tagalog (Filipino)' },
    { tg: 'Tajik' },
    { ta: 'Tamil' },
    { te: 'Telugu' },
    { th: 'Thai' },
    { tr: 'Turkish' },
    { uk: 'Ukrainian' },
    { ur: 'Urdu' },
    { uz: 'Uzbek' },
    { vi: 'Vietnamese' },
    { cy: 'Welsh' },
    { xh: 'Xhosa' },
    { yi: 'Yiddish' },
    { yo: 'Yoruba' },
    { zu: 'Zuluu' }
  ]
}
